artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/cd237543c1b44a13a1f4104070d3de6a/artifacts
end_time: 1676178044656
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: cd237543c1b44a13a1f4104070d3de6a
run_uuid: cd237543c1b44a13a1f4104070d3de6a
source_name: ''
source_type: 4
source_version: ''
start_time: 1676178044620
status: 3
tags: []
user_id: tony3
