artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/7566b65f28fb44f7a004b11d1695a225/artifacts
end_time: 1676256438206
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 7566b65f28fb44f7a004b11d1695a225
run_uuid: 7566b65f28fb44f7a004b11d1695a225
source_name: ''
source_type: 4
source_version: ''
start_time: 1676256438162
status: 3
tags: []
user_id: tony3
