artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/973fb8bbf6b64881b10a7b764b47437e/artifacts
end_time: 1676245627905
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 973fb8bbf6b64881b10a7b764b47437e
run_uuid: 973fb8bbf6b64881b10a7b764b47437e
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245627865
status: 3
tags: []
user_id: tony3
