artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/27b7fa4a0f724e16bc4fbdfd1aca44fd/artifacts
end_time: 1676245751246
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 27b7fa4a0f724e16bc4fbdfd1aca44fd
run_uuid: 27b7fa4a0f724e16bc4fbdfd1aca44fd
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245751204
status: 3
tags: []
user_id: tony3
