artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/4a296afa2ab34ba28eb22e5a0bf069ca/artifacts
end_time: 1676178049020
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 4a296afa2ab34ba28eb22e5a0bf069ca
run_uuid: 4a296afa2ab34ba28eb22e5a0bf069ca
source_name: ''
source_type: 4
source_version: ''
start_time: 1676178048982
status: 3
tags: []
user_id: tony3
