artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/394045718b634b3c97d0c5621e7f5c08/artifacts
end_time: 1676245608563
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 394045718b634b3c97d0c5621e7f5c08
run_uuid: 394045718b634b3c97d0c5621e7f5c08
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245608520
status: 3
tags: []
user_id: tony3
