# mkdocs.yml
site_name: Made With ML
site_url: https://madewithml.com/
repo_url: https://github.com/GokuMohandas/mlops-course/
nav:
  - Home: index.md
  - workflows:
    - main: tagifai/main.md
  - tagifai:
    - data: tagifai/data.md
    - evaluate: tagifai/evaluate.md
    - predict: tagifai/predict.md
    - train: tagifai/train.md
    - utils: tagifai/utils.md
  - configuration:
    - package: config/package.md
    - config: config/config.md
  - tests:
    - main: tests/main.md
    - data: tests/data.md
theme: readthedocs
plugins:
  - mkdocstrings
      # handlers:
      #   python:
      #     setup_commands:
      #       - import sys
      #       - sys.path.append("tests")
watch:
  - .  # reload docs for any file changes
