artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/b5da744c8efe4b4a90f405b241b88fdf/artifacts
end_time: 1676256426563
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: b5da744c8efe4b4a90f405b241b88fdf
run_uuid: b5da744c8efe4b4a90f405b241b88fdf
source_name: ''
source_type: 4
source_version: ''
start_time: 1676256426525
status: 3
tags: []
user_id: tony3
