artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/7f721ba9d1f64f23be9ae8692df5b3ca/artifacts
end_time: 1676245602195
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 7f721ba9d1f64f23be9ae8692df5b3ca
run_uuid: 7f721ba9d1f64f23be9ae8692df5b3ca
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245602156
status: 3
tags: []
user_id: tony3
