artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/9debebfd7fb84c7ebb68ffc42f2cded9/artifacts
end_time: 1676256434933
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 9debebfd7fb84c7ebb68ffc42f2cded9
run_uuid: 9debebfd7fb84c7ebb68ffc42f2cded9
source_name: ''
source_type: 4
source_version: ''
start_time: 1676256434891
status: 3
tags: []
user_id: tony3
