artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/9d993d29f34b453ba4ff4e3d02d7701f/artifacts
end_time: 1676245777444
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 9d993d29f34b453ba4ff4e3d02d7701f
run_uuid: 9d993d29f34b453ba4ff4e3d02d7701f
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245777404
status: 3
tags: []
user_id: tony3
