artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/7001e83385a4413d8c88f42c2550fa1f/artifacts
end_time: 1676178052014
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 7001e83385a4413d8c88f42c2550fa1f
run_uuid: 7001e83385a4413d8c88f42c2550fa1f
source_name: ''
source_type: 4
source_version: ''
start_time: 1676178051984
status: 3
tags: []
user_id: tony3
