artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/559522d1643443f69539511d1f510dec/artifacts
end_time: 1676245767128
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 559522d1643443f69539511d1f510dec
run_uuid: 559522d1643443f69539511d1f510dec
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245767067
status: 3
tags: []
user_id: tony3
