artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/505fa53e1def4e0c91439cf9e4548db9/artifacts
end_time: 1676178031621
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 505fa53e1def4e0c91439cf9e4548db9
run_uuid: 505fa53e1def4e0c91439cf9e4548db9
source_name: ''
source_type: 4
source_version: ''
start_time: 1676178031595
status: 3
tags: []
user_id: tony3
