artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/d17b8699859b4ae3945ac4645caf9d6b/artifacts
end_time: 1676178068248
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: d17b8699859b4ae3945ac4645caf9d6b
run_uuid: d17b8699859b4ae3945ac4645caf9d6b
source_name: ''
source_type: 4
source_version: ''
start_time: 1676178068204
status: 3
tags: []
user_id: tony3
