artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/efe53d8f25e9428193d373f1ef9da058/artifacts
end_time: 1676245607086
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: efe53d8f25e9428193d373f1ef9da058
run_uuid: efe53d8f25e9428193d373f1ef9da058
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245607048
status: 3
tags: []
user_id: tony3
