artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/06bc4a787a8c4df38782456275097f59/artifacts
end_time: 1676245748016
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 06bc4a787a8c4df38782456275097f59
run_uuid: 06bc4a787a8c4df38782456275097f59
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245747992
status: 3
tags: []
user_id: tony3
