artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/46ab5a351e974905822a8a99c5880d66/artifacts
end_time: 1676256410428
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 46ab5a351e974905822a8a99c5880d66
run_uuid: 46ab5a351e974905822a8a99c5880d66
source_name: ''
source_type: 4
source_version: ''
start_time: 1676256410388
status: 3
tags: []
user_id: tony3
