artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/38057dee79704c7f8846c67db8bbb9ab/artifacts
end_time: 1676256424421
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 38057dee79704c7f8846c67db8bbb9ab
run_uuid: 38057dee79704c7f8846c67db8bbb9ab
source_name: ''
source_type: 4
source_version: ''
start_time: 1676256424381
status: 3
tags: []
user_id: tony3
