artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/66abe4224c4d41e4bb4bad6a9ddd9c26/artifacts
end_time: 1676245780894
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 66abe4224c4d41e4bb4bad6a9ddd9c26
run_uuid: 66abe4224c4d41e4bb4bad6a9ddd9c26
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245780834
status: 3
tags: []
user_id: tony3
