artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/1e163cb5aef7400d8fc5a51714190388/artifacts
end_time: 1676245645349
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 1e163cb5aef7400d8fc5a51714190388
run_uuid: 1e163cb5aef7400d8fc5a51714190388
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245645308
status: 3
tags: []
user_id: tony3
