artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/a70cf6f518f140cea729253eb269ec67/artifacts
end_time: 1676178030358
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: a70cf6f518f140cea729253eb269ec67
run_uuid: a70cf6f518f140cea729253eb269ec67
source_name: ''
source_type: 4
source_version: ''
start_time: 1676178030336
status: 3
tags: []
user_id: tony3
