artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/56cf7cdc183f45b5b78791065ce2b363/artifacts
end_time: 1676256407604
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 56cf7cdc183f45b5b78791065ce2b363
run_uuid: 56cf7cdc183f45b5b78791065ce2b363
source_name: ''
source_type: 4
source_version: ''
start_time: 1676256407570
status: 3
tags: []
user_id: tony3
