artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/cfc7213fa44f4fe1842f682f336c5d86/artifacts
end_time: 1676245769975
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: cfc7213fa44f4fe1842f682f336c5d86
run_uuid: cfc7213fa44f4fe1842f682f336c5d86
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245769929
status: 3
tags: []
user_id: tony3
