artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/85840edf43e148eaaa1894fbf77234a2/artifacts
end_time: 1676245749615
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 85840edf43e148eaaa1894fbf77234a2
run_uuid: 85840edf43e148eaaa1894fbf77234a2
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245749579
status: 3
tags: []
user_id: tony3
