artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/c68ed2ca84384ca19dac6cb18af8dda6/artifacts
end_time: 1676256425151
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: c68ed2ca84384ca19dac6cb18af8dda6
run_uuid: c68ed2ca84384ca19dac6cb18af8dda6
source_name: ''
source_type: 4
source_version: ''
start_time: 1676256425110
status: 3
tags: []
user_id: tony3
