artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/f84edbb6823f4d949346e087a7574443/artifacts
end_time: 1676245778014
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: f84edbb6823f4d949346e087a7574443
run_uuid: f84edbb6823f4d949346e087a7574443
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245777966
status: 3
tags: []
user_id: tony3
