artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/04a2f6da6aa4492883899233a0470d03/artifacts
end_time: 1676178063907
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 04a2f6da6aa4492883899233a0470d03
run_uuid: 04a2f6da6aa4492883899233a0470d03
source_name: ''
source_type: 4
source_version: ''
start_time: 1676178063865
status: 3
tags: []
user_id: tony3
