artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/3/aae133b3516243a493904d9d27acb590/artifacts
end_time: 1678053090261
entry_point_name: ''
experiment_id: '3'
lifecycle_stage: active
name: ''
run_id: aae133b3516243a493904d9d27acb590
run_uuid: aae133b3516243a493904d9d27acb590
source_name: ''
source_type: 4
source_version: ''
start_time: 1678053086577
status: 3
tags: []
user_id: tony3
