artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/01c597be56b740aeabf7f65909448feb/artifacts
end_time: 1676256406249
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 01c597be56b740aeabf7f65909448feb
run_uuid: 01c597be56b740aeabf7f65909448feb
source_name: ''
source_type: 4
source_version: ''
start_time: 1676256406218
status: 3
tags: []
user_id: tony3
