artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/d9e3c107a19a40efa5dd8c5185a6cdd3/artifacts
end_time: 1676256449491
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: d9e3c107a19a40efa5dd8c5185a6cdd3
run_uuid: d9e3c107a19a40efa5dd8c5185a6cdd3
source_name: ''
source_type: 4
source_version: ''
start_time: 1676256449445
status: 3
tags: []
user_id: tony3
