artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/5b0a67ce367847b9b9dde29a95c4fbfe/artifacts
end_time: 1676245758840
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 5b0a67ce367847b9b9dde29a95c4fbfe
run_uuid: 5b0a67ce367847b9b9dde29a95c4fbfe
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245758800
status: 3
tags: []
user_id: tony3
