artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/a8bf050ee808493581791d9be74e0254/artifacts
end_time: 1676245620558
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: a8bf050ee808493581791d9be74e0254
run_uuid: a8bf050ee808493581791d9be74e0254
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245620521
status: 3
tags: []
user_id: tony3
