artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/00136283a86244a0b3e17944b5b8a800/artifacts
end_time: 1676245636868
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 00136283a86244a0b3e17944b5b8a800
run_uuid: 00136283a86244a0b3e17944b5b8a800
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245636827
status: 3
tags: []
user_id: tony3
