artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/694944defaa64509a9956cd8bbf5fe4f/artifacts
end_time: 1676245639520
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 694944defaa64509a9956cd8bbf5fe4f
run_uuid: 694944defaa64509a9956cd8bbf5fe4f
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245639479
status: 3
tags: []
user_id: tony3
