artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/3f8de0467f7c40c0a82d9d73d7e776c1/artifacts
end_time: 1676178057914
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 3f8de0467f7c40c0a82d9d73d7e776c1
run_uuid: 3f8de0467f7c40c0a82d9d73d7e776c1
source_name: ''
source_type: 4
source_version: ''
start_time: 1676178057880
status: 3
tags: []
user_id: tony3
