artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/aeadf2bdec554f22a4d3a868c0e9a201/artifacts
end_time: 1676245773849
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: aeadf2bdec554f22a4d3a868c0e9a201
run_uuid: aeadf2bdec554f22a4d3a868c0e9a201
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245773795
status: 3
tags: []
user_id: tony3
