artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/d874bd892ccf4e6cb3c2c6d8fe093c8d/artifacts
end_time: 1676245642862
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: d874bd892ccf4e6cb3c2c6d8fe093c8d
run_uuid: d874bd892ccf4e6cb3c2c6d8fe093c8d
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245642816
status: 3
tags: []
user_id: tony3
