artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/9acd4870f39e4a3c92ba3e6adc815806/artifacts
end_time: 1676178055119
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 9acd4870f39e4a3c92ba3e6adc815806
run_uuid: 9acd4870f39e4a3c92ba3e6adc815806
source_name: ''
source_type: 4
source_version: ''
start_time: 1676178055085
status: 3
tags: []
user_id: tony3
