artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/aa51357617a04a01820e73bc4f83db31/artifacts
end_time: 1676245604882
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: aa51357617a04a01820e73bc4f83db31
run_uuid: aa51357617a04a01820e73bc4f83db31
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245604844
status: 3
tags: []
user_id: tony3
