artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/20d8c19dae694aac95447e6e6cf9b5e2/artifacts
end_time: 1676245646095
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 20d8c19dae694aac95447e6e6cf9b5e2
run_uuid: 20d8c19dae694aac95447e6e6cf9b5e2
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245646047
status: 3
tags: []
user_id: tony3
