artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/ab6f4013dff64471aeba67df3688aa16/artifacts
end_time: 1676245615744
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: ab6f4013dff64471aeba67df3688aa16
run_uuid: ab6f4013dff64471aeba67df3688aa16
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245615705
status: 3
tags: []
user_id: tony3
