artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/83aabbd4996b45d1acea149e92f86f77/artifacts
end_time: 1676256445694
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 83aabbd4996b45d1acea149e92f86f77
run_uuid: 83aabbd4996b45d1acea149e92f86f77
source_name: ''
source_type: 4
source_version: ''
start_time: 1676256445651
status: 3
tags: []
user_id: tony3
