artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/3b60e22fbbac48fba1dda093d668189f/artifacts
end_time: 1676178061888
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 3b60e22fbbac48fba1dda093d668189f
run_uuid: 3b60e22fbbac48fba1dda093d668189f
source_name: ''
source_type: 4
source_version: ''
start_time: 1676178061797
status: 3
tags: []
user_id: tony3
