artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/2ae6ddd9273041a7891e9fd45bdb792a/artifacts
end_time: 1676256418269
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 2ae6ddd9273041a7891e9fd45bdb792a
run_uuid: 2ae6ddd9273041a7891e9fd45bdb792a
source_name: ''
source_type: 4
source_version: ''
start_time: 1676256418226
status: 3
tags: []
user_id: tony3
