artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/f4aaf83c8b37409fa6628382e475abfb/artifacts
end_time: 1676245634017
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: f4aaf83c8b37409fa6628382e475abfb
run_uuid: f4aaf83c8b37409fa6628382e475abfb
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245633975
status: 3
tags: []
user_id: tony3
