artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/331d017614294fa8b8daff04b96275f6/artifacts
end_time: 1676256415228
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 331d017614294fa8b8daff04b96275f6
run_uuid: 331d017614294fa8b8daff04b96275f6
source_name: ''
source_type: 4
source_version: ''
start_time: 1676256415181
status: 3
tags: []
user_id: tony3
