artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/1f24fbee07e4400180070a63d80487df/artifacts
end_time: 1676245774548
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 1f24fbee07e4400180070a63d80487df
run_uuid: 1f24fbee07e4400180070a63d80487df
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245774501
status: 3
tags: []
user_id: tony3
