artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/8c649e6da0644ceea36d14a32e8d2af3/artifacts
end_time: 1676256411972
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 8c649e6da0644ceea36d14a32e8d2af3
run_uuid: 8c649e6da0644ceea36d14a32e8d2af3
source_name: ''
source_type: 4
source_version: ''
start_time: 1676256411936
status: 3
tags: []
user_id: tony3
