artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/ba12d16f9df14e51af5636d712d55627/artifacts
end_time: 1676245621884
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: ba12d16f9df14e51af5636d712d55627
run_uuid: ba12d16f9df14e51af5636d712d55627
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245621852
status: 3
tags: []
user_id: tony3
