artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/22ea12ec8cf94f3bbfddd1dee935a8e1/artifacts
end_time: 1676245770521
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 22ea12ec8cf94f3bbfddd1dee935a8e1
run_uuid: 22ea12ec8cf94f3bbfddd1dee935a8e1
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245770480
status: 3
tags: []
user_id: tony3
