artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/3343098a5de44c4893a12af1bd7d9165/artifacts
end_time: 1676256415943
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 3343098a5de44c4893a12af1bd7d9165
run_uuid: 3343098a5de44c4893a12af1bd7d9165
source_name: ''
source_type: 4
source_version: ''
start_time: 1676256415898
status: 3
tags: []
user_id: tony3
