artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/bb053e7ef60c4eddad4bb95966da11b0/artifacts
end_time: 1676178066656
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: bb053e7ef60c4eddad4bb95966da11b0
run_uuid: bb053e7ef60c4eddad4bb95966da11b0
source_name: ''
source_type: 4
source_version: ''
start_time: 1676178066628
status: 3
tags: []
user_id: tony3
