artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/77ad4957ab8d481993c73a7196bc5cf2/artifacts
end_time: 1676245617114
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 77ad4957ab8d481993c73a7196bc5cf2
run_uuid: 77ad4957ab8d481993c73a7196bc5cf2
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245617075
status: 3
tags: []
user_id: tony3
