artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/c44963bc044140558ab3eb3557573b02/artifacts
end_time: 1676178047121
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: c44963bc044140558ab3eb3557573b02
run_uuid: c44963bc044140558ab3eb3557573b02
source_name: ''
source_type: 4
source_version: ''
start_time: 1676178047084
status: 3
tags: []
user_id: tony3
