artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/c189d85451bc40e8b0356461651bd434/artifacts
end_time: 1676245624869
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: c189d85451bc40e8b0356461651bd434
run_uuid: c189d85451bc40e8b0356461651bd434
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245624834
status: 3
tags: []
user_id: tony3
