artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/472ab77b7ead433b8655ca1d15202af6/artifacts
end_time: 1676256443032
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 472ab77b7ead433b8655ca1d15202af6
run_uuid: 472ab77b7ead433b8655ca1d15202af6
source_name: ''
source_type: 4
source_version: ''
start_time: 1676256442988
status: 3
tags: []
user_id: tony3
