artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/9139c9d9e45a42ff938db9833fff20bd/artifacts
end_time: 1676245756957
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 9139c9d9e45a42ff938db9833fff20bd
run_uuid: 9139c9d9e45a42ff938db9833fff20bd
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245756922
status: 3
tags: []
user_id: tony3
