artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/30df3f40416b488fb24071b4afcf9885/artifacts
end_time: 1676245791431
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 30df3f40416b488fb24071b4afcf9885
run_uuid: 30df3f40416b488fb24071b4afcf9885
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245791381
status: 3
tags: []
user_id: tony3
