artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/f9a57a4d2ef24ee087ea7ccf06f8bb71/artifacts
end_time: 1676178040992
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: f9a57a4d2ef24ee087ea7ccf06f8bb71
run_uuid: f9a57a4d2ef24ee087ea7ccf06f8bb71
source_name: ''
source_type: 4
source_version: ''
start_time: 1676178040951
status: 3
tags: []
user_id: tony3
