artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/f17ea6f71c1548cea01d73ad00925c8c/artifacts
end_time: 1676256451491
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: f17ea6f71c1548cea01d73ad00925c8c
run_uuid: f17ea6f71c1548cea01d73ad00925c8c
source_name: ''
source_type: 4
source_version: ''
start_time: 1676256451456
status: 3
tags: []
user_id: tony3
