artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/5e3e3ca4838f4aab813f573e09aa4c54/artifacts
end_time: 1676178037903
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 5e3e3ca4838f4aab813f573e09aa4c54
run_uuid: 5e3e3ca4838f4aab813f573e09aa4c54
source_name: ''
source_type: 4
source_version: ''
start_time: 1676178037856
status: 3
tags: []
user_id: tony3
