artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/c96fd256999b4ddbbd77399fe9d2d288/artifacts
end_time: 1676178034976
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: c96fd256999b4ddbbd77399fe9d2d288
run_uuid: c96fd256999b4ddbbd77399fe9d2d288
source_name: ''
source_type: 4
source_version: ''
start_time: 1676178034938
status: 3
tags: []
user_id: tony3
