artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/a339b3b7e0b1469dbe16433dd0023673/artifacts
end_time: 1676256429602
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: a339b3b7e0b1469dbe16433dd0023673
run_uuid: a339b3b7e0b1469dbe16433dd0023673
source_name: ''
source_type: 4
source_version: ''
start_time: 1676256429557
status: 3
tags: []
user_id: tony3
