artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/40f3de7bea8842719949983e1f638fca/artifacts
end_time: 1676245600608
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 40f3de7bea8842719949983e1f638fca
run_uuid: 40f3de7bea8842719949983e1f638fca
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245600577
status: 3
tags: []
user_id: tony3
