artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/bb675eb7b1cb4e40add8d5ff42456c6a/artifacts
end_time: 1676245630894
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: bb675eb7b1cb4e40add8d5ff42456c6a
run_uuid: bb675eb7b1cb4e40add8d5ff42456c6a
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245630861
status: 3
tags: []
user_id: tony3
