name: DVC Operations

on:
  push:
    branches:
      - dev-secret

jobs:
  dvc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup DVC
      uses: iterative/setup-dvc@v1

    - name: Setup Google Drive credentials
      env:
        GDRIVE_CLIENT_ID: ${{ secrets.GDRIVE_CLIENT_ID }}
        GDRIVE_CLIENT_SECRET: ${{ secrets.GDRIVE_CLIENT_SECRET }}
        GDRIVE_SERVICE_ACCOUNT_JSON: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON_FILE_PATH }}
      run: |
        echo "$GDRIVE_SERVICE_ACCOUNT_JSON" > dvc-remote-connections.json
        dvc remote modify storage gdrive_client_id $GDRIVE_CLIENT_ID
        dvc remote modify storage gdrive_client_secret $GDRIVE_CLIENT_SECRET
        dvc remote modify storage gdrive_service_account_json_file_path dvc-remote-connections.json

    - name: DVC Pull
      run: dvc pull

    - name: Upload data as artifact
      uses: actions/upload-artifact@v2
      with:
        name: pulled-data
        path: data/