artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/b59578d34ab34d34bc926d326923a970/artifacts
end_time: 1676245597041
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: b59578d34ab34d34bc926d326923a970
run_uuid: b59578d34ab34d34bc926d326923a970
source_name: ''
source_type: 4
source_version: ''
start_time: 1676245597018
status: 3
tags: []
user_id: tony3
