artifact_uri: file:///Users/tony3/Library/CloudStorage/OneDrive-Personal/OneDrive
  Documents/MadewithML/mlops/stores/model/2/caa9e7bd4de84986b2fce52594782186/artifacts
end_time: 1676256440440
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: caa9e7bd4de84986b2fce52594782186
run_uuid: caa9e7bd4de84986b2fce52594782186
source_name: ''
source_type: 4
source_version: ''
start_time: 1676256440395
status: 3
tags: []
user_id: tony3
